### PR TITLE
Added image processing file to add noise to picture

### PR DESCRIPTION
**Pull request by achung98**
The current function returns a the noisy picture as a a array of type float64. Meaning the values are betwen [0, 1]. Let me know if you need them normalized to [0-255]

If you want to see the pictures with the noise, you can uncomment lines 40-41. It will display the picture.

The function apply_noise is the main function and need the image path in order to function.

### CODE REVIEW

**Comment by GwenLegate** [comment]
applied the noise function to one of the images and took a look.

image

The different lighting like Dirk was suggesting should help the accuracy.  
I added code to incorporate it into the preprocessing steps for the digit and alphabet training images:

image

**Comment by achung98** [comment]
Do you think we should add the nosie to every image? Or should we add noise to some of the pictures randomly?

Also, I realized that i shouldnt have created a new file. I could've just added the functionality to the prepocess_image function. Will do that later today.

**Comment by GwenLegate** [comment]
I added the code to preprocess training images instead, preprocess image I want to keep independent since it's being used to preprocess all the images, including the test images and we don't want to add noise to those.

I'm not sure if we should add noise to all the images or not, I was wondering about that too.  I'm going to do smaller runs like the hyper parameter search where I try different mixes of preprocessing to see what happens.

**Comment by achung98** [comment]
> I added the code to preprocess training images instead, preprocess image I want to keep independent since it's being used to preprocess all the images, including the test images and we don't want to add noise to those.
> 
> I'm not sure if we should add noise to all the images or not, I was wondering about that too. I'm going to do smaller runs like the hyper parameter search where I try different mixes of preprocessing to see what happens. I'm also wondering about which "type" of noise might help the most and if we should combine them or favour one over the others

If you noticed, i kind of apply different types of noise randomly to the pictures. It would randomly get a number from 0-2 and depending on the number it will apply that type of filter. The internsity of the noise is also randomized (From 1 to 100). If we wanted to have some pictures without noise, we can simply add another option (say 3) that will just return the picture. That way, some pictures (or none, depends on the randomness) will have no noise.

**Comment by GwenLegate** [comment]
> > I added the code to preprocess training images instead, preprocess image I want to keep independent since it's being used to preprocess all the images, including the test images and we don't want to add noise to those.
> > I'm not sure if we should add noise to all the images or not, I was wondering about that too. I'm going to do smaller runs like the hyper parameter search where I try different mixes of preprocessing to see what happens. I'm also wondering about which "type" of noise might help the most and if we should combine them or favour one over the others
> 
> If you noticed, i kind of apply different types of noise randomly to the pictures. It would randomly get a number from 0-2 and depending on the number it will apply that type of filter. The internsity of the noise is also randomized (From 1 to 100). If we wanted to have some pictures without noise, we can simply add another option (say 3) that will just return the picture. That way, some pictures (or none, depends on the randomness) will have no noise.

I noticed the randomized noise intensity, from the sounds of what Dirk was saying, the noise intensity  variation is the most important thing.  Some un-noisy images might help with clear feature detection so it might be a good idea to have them.  

I'm not sure how much processing this could save but I was thinking since apply_noise() and preprocess_image() are separate calls it might help with the processing time just to skip the apply noise function in, say the first 10% of images in each directory.  The processing time is long and if we can bypass a step completely that might help.  There are so many images!  Especially in the letters set

**Comment by achung98** [comment]
> > > I added the code to preprocess training images instead, preprocess image I want to keep independent since it's being used to preprocess all the images, including the test images and we don't want to add noise to those.
> > > I'm not sure if we should add noise to all the images or not, I was wondering about that too. I'm going to do smaller runs like the hyper parameter search where I try different mixes of preprocessing to see what happens. I'm also wondering about which "type" of noise might help the most and if we should combine them or favour one over the others
> > 
> > 
> > If you noticed, i kind of apply different types of noise randomly to the pictures. It would randomly get a number from 0-2 and depending on the number it will apply that type of filter. The internsity of the noise is also randomized (From 1 to 100). If we wanted to have some pictures without noise, we can simply add another option (say 3) that will just return the picture. That way, some pictures (or none, depends on the randomness) will have no noise.
> 
> I noticed the randomized noise intensity, from the sounds of what Dirk was saying, the noise intensity variation is the most important thing. Some un-noisy images might help with clear feature detection so it might be a good idea to have them.
> 
> I'm not sure how much processing this could save but I was thinking since apply_noise() and preprocess_image() are separate calls it might help with the processing time just to skip the apply noise function in, say the first 10% of images in each directory. The processing time is long and if we can bypass a step completely that might help. There are so many images! Especially in the letters set

I agree about the unoinsy images. I'll make the changes and create the pr shortly.

About performance, that is true, I would guess that with the added overhead of the apply_noise function, it takes a lot to preprocess the image. My question is, would applying the nosie to always the first 10% of the pictures create some sort of bias in our model?, instead of that, i can add some sort of "weight" in the apply_noise, say 90% of the time it will not add noise to the picture. I think that would be a better idea and improve the performance a bit.

**Comment by GwenLegate** [comment]
> > > > I added the code to preprocess training images instead, preprocess image I want to keep independent since it's being used to preprocess all the images, including the test images and we don't want to add noise to those.
> > > > I'm not sure if we should add noise to all the images or not, I was wondering about that too. I'm going to do smaller runs like the hyper parameter search where I try different mixes of preprocessing to see what happens. I'm also wondering about which "type" of noise might help the most and if we should combine them or favour one over the others
> > > 
> > > 
> > > If you noticed, i kind of apply different types of noise randomly to the pictures. It would randomly get a number from 0-2 and depending on the number it will apply that type of filter. The internsity of the noise is also randomized (From 1 to 100). If we wanted to have some pictures without noise, we can simply add another option (say 3) that will just return the picture. That way, some pictures (or none, depends on the randomness) will have no noise.
> > 
> > 
> > I noticed the randomized noise intensity, from the sounds of what Dirk was saying, the noise intensity variation is the most important thing. Some un-noisy images might help with clear feature detection so it might be a good idea to have them.
> > I'm not sure how much processing this could save but I was thinking since apply_noise() and preprocess_image() are separate calls it might help with the processing time just to skip the apply noise function in, say the first 10% of images in each directory. The processing time is long and if we can bypass a step completely that might help. There are so many images! Especially in the letters set
> 
> I agree about the unoinsy images. I'll make the changes and create the pr shortly.
> 
> About performance, that is true, I would guess that with the added overhead of the apply_noise function, it takes a lot to preprocess the image. My question is, would applying the nosie to always the first 10% of the pictures create some sort of bias in our model?, instead of that, i can add some sort of "weight" in the apply_noise, say 90% of the time it will not add noise to the picture. I think that would be a better idea and improve the performance a bit.

I think I wrote it backwards, I meant to apply noise 90% of the time like you said.  T thought about the bias of just skipping the first 10% but I don't think it will matter as long as it's the first 10% of A's and B' and C's etc...  I think bias would only be a problem if we skipped the first 10% of the dataset because then it would predict things like "A's never have noise"

**Comment by achung98** [comment]
> > > > > I added the code to preprocess training images instead, preprocess image I want to keep independent since it's being used to preprocess all the images, including the test images and we don't want to add noise to those.
> > > > > I'm not sure if we should add noise to all the images or not, I was wondering about that too. I'm going to do smaller runs like the hyper parameter search where I try different mixes of preprocessing to see what happens. I'm also wondering about which "type" of noise might help the most and if we should combine them or favour one over the others
> > > > 
> > > > 
> > > > If you noticed, i kind of apply different types of noise randomly to the pictures. It would randomly get a number from 0-2 and depending on the number it will apply that type of filter. The internsity of the noise is also randomized (From 1 to 100). If we wanted to have some pictures without noise, we can simply add another option (say 3) that will just return the picture. That way, some pictures (or none, depends on the randomness) will have no noise.
> > > 
> > > 
> > > I noticed the randomized noise intensity, from the sounds of what Dirk was saying, the noise intensity variation is the most important thing. Some un-noisy images might help with clear feature detection so it might be a good idea to have them.
> > > I'm not sure how much processing this could save but I was thinking since apply_noise() and preprocess_image() are separate calls it might help with the processing time just to skip the apply noise function in, say the first 10% of images in each directory. The processing time is long and if we can bypass a step completely that might help. There are so many images! Especially in the letters set
> > 
> > 
> > I agree about the unoinsy images. I'll make the changes and create the pr shortly.
> > About performance, that is true, I would guess that with the added overhead of the apply_noise function, it takes a lot to preprocess the image. My question is, would applying the nosie to always the first 10% of the pictures create some sort of bias in our model?, instead of that, i can add some sort of "weight" in the apply_noise, say 90% of the time it will not add noise to the picture. I think that would be a better idea and improve the performance a bit.
> 
> I think I wrote it backwards, I meant to apply noise 90% of the time like you said. T thought about the bias of just skipping the first 10% but I don't think it will matter as long as it's the first 10% of A's and B' and C's etc... I think bias would only be a problem if we skipped the first 10% of the dataset because then it would predict things like "A's never have noise"

I see. What do you think then, should I add he "weighted" 90% or should we just always skip the first 10%?

**Comment by GwenLegate** [comment]
> > > > > > I added the code to preprocess training images instead, preprocess image I want to keep independent since it's being used to preprocess all the images, including the test images and we don't want to add noise to those.
> > > > > > I'm not sure if we should add noise to all the images or not, I was wondering about that too. I'm going to do smaller runs like the hyper parameter search where I try different mixes of preprocessing to see what happens. I'm also wondering about which "type" of noise might help the most and if we should combine them or favour one over the others
> > > > > 
> > > > > 
> > > > > If you noticed, i kind of apply different types of noise randomly to the pictures. It would randomly get a number from 0-2 and depending on the number it will apply that type of filter. The internsity of the noise is also randomized (From 1 to 100). If we wanted to have some pictures without noise, we can simply add another option (say 3) that will just return the picture. That way, some pictures (or none, depends on the randomness) will have no noise.
> > > > 
> > > > 
> > > > I noticed the randomized noise intensity, from the sounds of what Dirk was saying, the noise intensity variation is the most important thing. Some un-noisy images might help with clear feature detection so it might be a good idea to have them.
> > > > I'm not sure how much processing this could save but I was thinking since apply_noise() and preprocess_image() are separate calls it might help with the processing time just to skip the apply noise function in, say the first 10% of images in each directory. The processing time is long and if we can bypass a step completely that might help. There are so many images! Especially in the letters set
> > > 
> > > 
> > > I agree about the unoinsy images. I'll make the changes and create the pr shortly.
> > > About performance, that is true, I would guess that with the added overhead of the apply_noise function, it takes a lot to preprocess the image. My question is, would applying the nosie to always the first 10% of the pictures create some sort of bias in our model?, instead of that, i can add some sort of "weight" in the apply_noise, say 90% of the time it will not add noise to the picture. I think that would be a better idea and improve the performance a bit.
> > 
> > 
> > I think I wrote it backwards, I meant to apply noise 90% of the time like you said. T thought about the bias of just skipping the first 10% but I don't think it will matter as long as it's the first 10% of A's and B' and C's etc... I think bias would only be a problem if we skipped the first 10% of the dataset because then it would predict things like "A's never have noise"
> 
> I see. What do you think then, should I add he "weighted" 90% or should we just always skip the first 10%?

I was thinking of a counter and an if statement until we reach 10% but that might actually be more processing than just a weighted 90% and it would definitely be messier code.  if you add the weighted 90% I think that's better from a memory, processing and code cleanliness perspective.

**Comment by achung98** [comment]
> > > > > > > I added the code to preprocess training images instead, preprocess image I want to keep independent since it's being used to preprocess all the images, including the test images and we don't want to add noise to those.
> > > > > > > I'm not sure if we should add noise to all the images or not, I was wondering about that too. I'm going to do smaller runs like the hyper parameter search where I try different mixes of preprocessing to see what happens. I'm also wondering about which "type" of noise might help the most and if we should combine them or favour one over the others
> > > > > > 
> > > > > > 
> > > > > > If you noticed, i kind of apply different types of noise randomly to the pictures. It would randomly get a number from 0-2 and depending on the number it will apply that type of filter. The internsity of the noise is also randomized (From 1 to 100). If we wanted to have some pictures without noise, we can simply add another option (say 3) that will just return the picture. That way, some pictures (or none, depends on the randomness) will have no noise.
> > > > > 
> > > > > 
> > > > > I noticed the randomized noise intensity, from the sounds of what Dirk was saying, the noise intensity variation is the most important thing. Some un-noisy images might help with clear feature detection so it might be a good idea to have them.
> > > > > I'm not sure how much processing this could save but I was thinking since apply_noise() and preprocess_image() are separate calls it might help with the processing time just to skip the apply noise function in, say the first 10% of images in each directory. The processing time is long and if we can bypass a step completely that might help. There are so many images! Especially in the letters set
> > > > 
> > > > 
> > > > I agree about the unoinsy images. I'll make the changes and create the pr shortly.
> > > > About performance, that is true, I would guess that with the added overhead of the apply_noise function, it takes a lot to preprocess the image. My question is, would applying the nosie to always the first 10% of the pictures create some sort of bias in our model?, instead of that, i can add some sort of "weight" in the apply_noise, say 90% of the time it will not add noise to the picture. I think that would be a better idea and improve the performance a bit.
> > > 
> > > 
> > > I think I wrote it backwards, I meant to apply noise 90% of the time like you said. T thought about the bias of just skipping the first 10% but I don't think it will matter as long as it's the first 10% of A's and B' and C's etc... I think bias would only be a problem if we skipped the first 10% of the dataset because then it would predict things like "A's never have noise"
> > 
> > 
> > I see. What do you think then, should I add he "weighted" 90% or should we just always skip the first 10%?
> 
> I was thinking of a counter and an if statement until we reach 10% but that might actually be more processing than just a weighted 90% and it would definitely be messier code. if you add the weighted 90% I think that's better from a memory, processing and code cleanliness perspective.

Sounds good!

**Pull request merged**
